apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - image: snowflake:1.0.0
      name: app
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
